default["domain"] = "dwbru.net"
# WARN used in firewall cookbook
#          "ufw",
default["usefulPackages"] = [
          "zsh",
          "git",
          "bash-completion",
          "command-not-found",
          "man-db",
          "iptables",
          "psmisc",
          "acl",
          "telnet",
          "wget",
          "dnsutils",
          "traceroute",
          "lsof",
          "mlocate",
          "rsync",
          "ncurses-term",
          "vim",
          "dstat",
          "apt-file",
          "makepasswd",
          "unattended-upgrades",
          "postfix",
          "bsd-mailx",
          "mysql-server",
          "nginx",
          "php5-fpm",
          "php5-mysql",
          "php5-mcrypt",
          "php5-gd",
          "php5-json",
          "libapache2-mod-macro",
          "libapache2-mod-php5",
          "postgresql",
          "pgtune",
          "vsftpd"
]